server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parking
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    show-sql: true

    #spring:
    #  datasource:
    #    url: jdbc:mysql://up2ovi0k86ju7shs:eDdpvHL2JQEpk4vIkfaf@bxe9edlcgpif4rkxiwwf-mysql.services.clever-cloud.com:3306/bxe9edlcgpif4rkxiwwf
    #    username: up2ovi0k86ju7shs
    #    password: eDdpvHL2JQEpk4vIkfaf
    #    driver-class-name: com.mysql.cj.jdbc.Driver